
version: 2.1
jobs:  
  create_infrastructure:
    docker:
      - image: "amazon/aws-cli"
    steps:
      - run:
          name: Ensure backend infrastructure exist
          command: |
          aws cloudformation create-stack --stack-name "InfastructureCreation" --template-body file://template.yml --region=us-west-2

workflows:
  create_infrastructure:
    jobs:
        -  create_infrastructure