
version: 2.1
jobs:  
  configure_infrastructure:
    docker:
      - image: "python:3.7-alpine3.11"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["fa:c5:cc:7e:24:a8:cc:94:96:83:79:61:9b:8a:8e:90"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.txt main.yml
      # - run:
      #     name: Ensure backend infrastructure exist
      #     command: aws cloudformation create-stack --stack-name "InfastructureCreation" --template-body file://template.yml
  smoke_test:
    docker:
      - image: "alpine:latest"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["fa:c5:cc:7e:24:a8:cc:94:96:83:79:61:9b:8a:8e:90"]
      - run:
          name: Check if website is accessable
          script: |
            if curl -s --head "ec2-54-202-105-115.us-west-2.compute.amazonaws.com:3000" 
            then 
              echo "It worked!" 
              return 0 
            else 
              echo "It failed" 
              return 1 
            fi

      

workflows:
  myWorkflow:
    jobs:
        - configure_infrastructure
        - smoke_test